// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmvzoqqgpixgqqyydsgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptdnpvcXFncGl4Z3FxeXlkc2dyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTI4NzIsImV4cCI6MjA2OTcyODg3Mn0.wKh5zRv7IMd7x5cZ_-0CJl03M8RmiNC9lCONkIEkyNw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});